;;; UNRUS - Thaw every layer in every viewport on every layout (clears all VP freezes)
;;; Global layer freeze/thaw is not touched.

(defun c:UNRUS (/ *error* doc oldtab oldecho)
  (vl-load-com)
  (setq doc     (vla-get-ActiveDocument (vlax-get-acad-object))
        oldtab  (getvar "CTAB")
        oldecho (getvar "CMDECHO"))
  (defun *error* (msg)
    (setvar "CTAB" oldtab)
    (setvar "CMDECHO" oldecho)
    (vla-EndUndoMark doc)
    (if (not (wcmatch (strcase msg) "*BREAK*,*CANCEL*,*EXIT*"))
      (princ (strcat "\nError: " msg)))
    (princ))
  (vla-StartUndoMark doc)
  (setvar "CMDECHO" 0)
  (foreach lay (layoutlist)
    (setvar "CTAB" lay)
    (command "_.VPLAYER" "_Thaw" "*" "_All" ""))
  (setvar "CTAB" oldtab)
  (setvar "CMDECHO" oldecho)
  (vla-EndUndoMark doc)
  (princ (strcat "\nThawed all viewport-frozen layers on " (itoa (length (layoutlist))) " layout(s)."))
  (princ))

(princ "\nUNRUS loaded.")
(princ)
